# Generated by Django 3.0.3 on 2020-02-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200229_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.AddField(
            model_name='patient',
            name='has_coronavirus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='places_list',
            field=models.TextField(default='[]'),
        ),
    ]
